### ISSUE TITLE
Suggested fix so will compile correctly gcc 5.3 c++14 ubuntu 16.04 (currently with error)

### ISSUE THREAD

**Issue by abarak-biu** [encryptogroup/ABY#68] opened 2018-07-25 11:07 UTC
I get the following error:

/home/ab/ABY/src/abycore/circuit/booleancircuits.cpp:2139:42: error: cannot call member function ‘uint32_t BooleanCircuit::PutSizeOptimizedGTGate(std::vector<unsigned int>, std::vector<unsigned int>)’ without object
     uint32_t cmp = (m_eContext == S_YAO) ?
                                          ^
/home/ab/ABY/src/abycore/circuit/booleancircuits.cpp:2139:42: error: cannot call member function ‘uint32_t BooleanCircuit::PutDepthOptimizedGTGate(std::vector<unsigned int>, std::vector<unsigned int>)’ without object
/home/ab/ABY/src/abycore/circuit/booleancircuits.cpp:2142:32: error: cannot call member function ‘std::vector<unsigned int> BooleanCircuit::PutMUXGate(std::vector<unsigned int>, std::vector<unsigned int>, uint32_t, BOOL)’ without object
     return PutMUXGate(a, b, cmp);
                                ^
/home/ab/ABY/src/abycore/circuit/booleancircuits.cpp: In member function ‘std::vector<unsigned int> BooleanCircuit::PutMaxGate(const std::vector<std::vector<unsigned int> >&)’:
/home/ab/ABY/src/abycore/circuit/booleancircuits.cpp:2143:4: error: conversion from ‘BooleanCircuit::PutMaxGate(const std::vector<std::vector<unsigned int> >&)::<lambda(auto:1, auto:2)>’ to non-scalar type ‘BinaryOp_v_uint32_t {aka std::function<std::vector<unsigned int>(const std::vector<unsigned int>&, const std::vector<unsigned int>&)>}’ requested

to fix this, I added "this->" in line ~2140 in booleancircuits.cpp

	BinaryOp_v_uint32_t op = [this](auto a, auto b) {
				uint32_t cmp = (m_eContext == S_YAO) ?
					this->PutSizeOptimizedGTGate(a, b) :
					this->PutDepthOptimizedGTGate(a, b);
				return this->PutMUXGate(a, b, cmp);

**Comment by lenerd** [comment] 2018-07-25 14:30
Hi,
I can reproduce this problem with GCC 5.4.1 which seems to be [this](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67274) GCC bug (fixed in 7.1.0).
It should not hurt to to make `this->` explicit here.

**Comment by lenerd** [comment] 2018-07-25 14:42
Fixed with ddecdd6.

**Closed as completed by lenerd** 2018-07-25 14:42 UTC

**Comment by abarak-biu** [comment] 2018-07-26 07:00
thanks



On 25 Jul 2018 5:42 p.m., "Lennart Braun" <notifications@github.com> wrote:

Closed #68 <https://github.com/encryptogroup/ABY/issues/68>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/encryptogroup/ABY/issues/68#event-1752788393>, or mute
the thread
