### ISSUE TITLE
Error when running abyfloat_test.exe

### ISSUE THREAD

**Issue by Cestlaviez** [encryptogroup/ABY#83] opened 2018-08-22 20:16 UTC
When I try to run abyfloat_test.exe from two terminals, I got an error.
```
~/ABY/build/bin$ ./abyfloat_test -r 0 -x 1.0 -y 2.1
double input values: 1.000 ; 2.100
Error: Unable to open circuit file circ/fp_nostatus_add_64.aby
Complexities: 
Boolean Sharing: ANDs: 0 (1-bit) ; Depth: 1
Total Vec AND: 0
Total Non-Vec AND: 0
XOR vals: 0 gates: 0
Comb gates: 0, CombStruct gates: 0, Perm gates: 0, Subset gates: 0, Split gates: 0
Yao: ANDs: 0 ; Depth: 0
Reverse Yao: ANDs: 0 ; Depth: 0
Arithmetic Sharing: MULs: 0 ; Depth: 0
SP-LUT Sharing: OT-gates: Total OT gates = 0; Depth: 1
Total number of gates: 128 Total depth: 1
Timings: 
Total =		0.493 ms
Init =		0.131 ms
CircuitGen =	0.033 ms
Network =	9498.035 ms
BaseOTs =	232.259 ms
Setup =		0.178 ms
OTExtension =	0.150 ms
Garbling =	0.000 ms
Online =	0.315 ms

Segmentation fault (core dumped)
```
There is an error "Error: Unable to open circuit file circ/fp_nostatus_add_64.aby". 
When I check the file, there isn't such a file. What is this file?

**Comment by lenerd** [comment] 2018-08-22 20:33
Hi,
you are looking for [this file](https://github.com/encryptogroup/ABY/blob/447bfc1f849c4f20734444a2a0869ac0fb0a4eb1/bin/circ/fp_ieee_add_64.aby) containing the description of a floating point addition circuit. If you copy/link the [bin/circ](https://github.com/encryptogroup/ABY/tree/447bfc1f849c4f20734444a2a0869ac0fb0a4eb1/bin/circ) directory into the working directory of the application, it should work.

Unfortunately, the path is hardcoded and there is currently no runtime option to change it.

**Comment by Cestlaviez** [comment] 2018-08-23 03:30
Hi,
Thanks. I found it and it work. 
Btw, do you know the definition of the files under the bin/circ directory?  I am trying to use ```fp_nostatus_cmp_64.aby``` to do cmp, but the result is 0 no matter what I input.

**Comment by lenerd** [comment] 2018-08-23 12:09
I cannot help you with these circuits. Maybe you can find the information [here](https://github.com/encryptogroup/ABY/blob/public/bin/circ/circuitformat.md) or in the corresponding [paper](https://dl.acm.org/citation.cfm?id=2813678)

**Comment by dd23** [comment] 2018-08-26 17:24
The `fp_nostatus_cmp_64.aby` should get two FP inputs, similar to the addition gate in the [float example](https://github.com/encryptogroup/ABY/blob/public/src/examples/float/abyfloat.cpp#L104).
The result is a single bit that indicates if one value `a` is bigger than the other `b`. I have to test if 1 means `a`>`b` or `a`<`b` and how `a`==`b` is handled.
I haven't used the FP circuits in a while, so I'm not 100% sure on the current status.

**Comment by Cestlaviez** [comment] 2018-08-27 02:51
Thanks, I have tested other functions in FP circuits. They can work except function CMP. 
Thus, I am wondering if someone have tested it successfully.

**Comment by dd23** [comment] 2019-05-17 13:02
I have added some example code to the float example in 8aa003c2e145c6d43b6ec73ef75618be43951b1d

The CMP works as intended. 
CMP(a,b) returns
1 if a>b
0 if a==b
0 if a<b

Please check if this works for you and if so, please close this issue.

**Closed as completed** 2020-08-26 15:01 UTC
