### ISSUE TITLE
Incorrect SIMD FP Multiplications in YAO Sharing

### ISSUE THREAD

**Issue by atreiber94** [encryptogroup/ABY#79] opened 2018-08-13 15:06 UTC
When doing SIMD FloatingPoint Multiplications in YAO Sharing, some of the resulting values are incorrect. Here is a small example that reproduces the issue (run e.g. with nvals=3): 

	int32_t test_float_circuit(e_role role, const std::string &address, uint16_t port, seclvl seclvl,
         uint32_t nvals, uint32_t nthreads, e_mt_gen_alg mt_alg) {

        	double afp, bfp;
		uint64_t *aptr, *bptr;
		uint32_t bitlen = 64; // values are double --> 64 bit.

		ABYParty* party = new ABYParty(role, address, port, seclvl, bitlen, nthreads,
			mt_alg);

		std::vector<Sharing*>& sharings = party->GetSharings();

		BooleanCircuit* yc = (BooleanCircuit*) sharings[S_YAO]->GetCircuitBuildRoutine();

		srand(time(NULL));

		uint64_t avals[nvals];
		uint64_t bvals[nvals];
		double cvals[nvals];

		for (int i = 0; i < nvals; ++i)
		{
			afp = ((float) rand()) / (float) RAND_MAX;
			bfp = ((float) rand()) / (float) RAND_MAX;

			aptr = (uint64_t*) &afp;
			bptr = (uint64_t*) &bfp;

			avals[i] = *aptr;
			bvals[i] = *bptr;
			cvals[i] = afp*bfp;
		}

		share* ain = yc->PutSIMDINGate(nvals, avals, bitlen, SERVER);
		share* bin = yc->PutSIMDINGate(nvals, bvals, bitlen, CLIENT);

		share* c = yc->PutFPGate(ain, bin, MUL, bitlen, nvals, no_status);

		share* res_out = yc->PutOUTGate(c, ALL);

		// run SMPC
		party->ExecCircuit();

		// retrieve plain text output
		uint32_t out_bitlen, out_nvals;
		uint64_t *out_vals;
		res_out->get_clear_value_vec(&out_vals, &out_bitlen, &out_nvals);

		for (uint32_t i = 0; i < nvals; i++) {

			// dereference output value as double without casting the content
			double val = *((double*) &out_vals[i]);

			std::cout << "RES: " << val << " Verification: " << cvals[i] << std::endl;
		}

		return 0;
	} 

Example output:

> RES: 0.184405 Verification: 0.184405
RES: 0.000746032 Verification: 0.00298413
RES: 0.0246997 Verification: 0.0987986

Sometimes all the results are correct, sometimes one or two results are incorrect. However the first result seems to always be correct? Using the same values for every dimension also works without issues.

**Comment by Jamie-Cui** [comment] 2019-03-19 08:25
HI, I encountered with the same issue the other day. Here's my explanation:

Let's say Alice has a float number A and Bob has a float number B, they want to securely calculate `A*B`.

1. Alice run your protocol and generates two random number `afp` (denoted as afp_a) and `bfp` (denoted as bfp_a).
2. Bob run your protocol and generates two another random number `afp` (denoted as afp_b) and `bfp` (denoted as bfp_b).

You should notice that those two pairs of randomly generated numbers are not the same. What you really want is calculating  `afp_a * bfp_b` while the verification in your code only calculates `afp_a * bfp_a` or `afp_b * bfp_b` which is not the same.

**Comment by dd23** [comment] 2019-05-03 12:09
I can confirm that there is a problem with the FP gates using Yao sharing and SIMD gates (with nvals>1). The first result does indeed always seem to be correct, while the following are likely to be incorrect.
I have updated the code above to work with the current FP code.

We will investigate this.

As @Jamie-Cui mentioned a failing verification can be caused, when client and server start at different times (since randomness here is seeded with time(NULL) ), but that is a different problem. The above-mentioned issue also occurs when both parties start at the same time and input identical values.

**Comment by krantikiran** [comment] 2020-06-20 14:18
@dd23  Could you please comment if the issue of using FP gates with YAO sharing has been resolved.

**Comment by dd23** [comment] 2020-06-23 17:46
PR #149 has fixed this. In fact, it is identical to the commit of @oliver-schick referenced above.

The problem is fixed, therefore I'll close this issue.

**Closed as completed by dd23** 2020-06-23 17:46 UTC
